service: townhub-api-shuttle

provider:
  name: aws
  runtime: ${file(../shared/provider.yml):runtime}
  region: ${file(../shared/provider.yml):region}
  profile: ${file(../shared/provider.yml):profile}
  stage: ${file(../shared/provider.yml):stage}
  apiGateway: ${file(../shared/api-gateway.yml)}
  environment:
    SHUTTLE_STOP_DATABASE_NAME: ${self:custom.shuttles.tables.stops.name}
    SHUTTLE_ROUTE_DATABASE_NAME: ${self:custom.shuttles.tables.routes.name}
    SHUTTLE_SCHEDULE_DATABASE_NAME: ${self:custom.shuttles.tables.schedules.name}
    SHUTTLE_DAILY_SCHEDULE_DATABASE_NAME: ${self:custom.shuttles.tables.dailySchedules.name}
  iamRoleStatements:
    - ${self:custom.shuttles.tableIamRoles.stopsTable}
    - ${self:custom.shuttles.tableIamRoles.routesTable}
    - ${self:custom.shuttles.tableIamRoles.schedulesTable}
    - ${self:custom.shuttles.tableIamRoles.dailySchedulesTable}

package:
  individually: true

custom:
  cors: ${file(../shared/cors.yml)}
  shuttles: ${file(../shared/features.yml):shuttles}
  rollup:
    config: ../../build/rollup.config.js
    installCommand: yarn add

plugins:
  - serverless-rollup-plugin

functions:
  getDailyData:
    handler: src/get-daily-data.main
    events:
      - http:
          path: shuttles/daily/:timestamp
          method: get
          cors: ${self:custom.cors}
